In [3]:
print("Mari Kita Mulai")

Mari Kita Mulai


In [4]:
string_1 = 'string dengan petik tunggal'
string_2 = "string dengan petik ganda"
string_3 = """string dengan petik tiga"""

In [5]:
string_1 = 'Petik tunggal \'escape\', petik ganda "OK"'
string_2 = "Petik tunggal 'OK', petik ganda \"escape\""
string_3 = """Mahasiswa pertama \n Mahasiswa kedua"""

print("string 1: ",string_1, "\nstring 2: ", string_2, "\nstring 3: ", string_3)

string 1:  Petik tunggal 'escape', petik ganda "OK" 
string 2:  Petik tunggal 'OK', petik ganda "escape" 
string 3:  Mahasiswa pertama 
 Mahasiswa kedua


In [6]:
tipe_string = "kelas D3 TI 2020"
print("data : ", tipe_string, "bertipe : ", type(tipe_string))

data :  kelas D3 TI 2020 bertipe :  <class 'str'>


In [7]:
tipe_integer = 1
print("data :", tipe_integer, "bertipe :", type(tipe_integer))

tipe_float = 2.5
print("data :", tipe_float, "bertipe :", type(tipe_float))

tipe_complex = complex(1, 9)
print("data :", tipe_complex, "bertipe :", type(tipe_complex))

data : 1 bertipe : <class 'int'>
data : 2.5 bertipe : <class 'float'>
data : (1+9j) bertipe : <class 'complex'>


In [1]:
tipe_bool = True
print("data :", tipe_bool, "bertipe :", type(tipe_bool))

data : True bertipe : <class 'bool'>


In [4]:
mahasiswa = {
    'D3 TI 2019': 'Victor Desrony',
    'D3 TI 2020': 'Matthew Alfredo'
}

mahasiswa['D3 TI 2020']

'Matthew Alfredo'

In [6]:
#Akan sangat lama jika menulis kumpulan data seperti ini
tinggi_badan_mahasiswa1 = 165
tinggi_badan_mahasiswa2 = 163
tinggi_badan_mahasiswa3 = 170
tinggi_badan_mahasiswa4 = 180
tinggi_badan_mahasiswa5 = 185
print("data tinggi badan mahasiswa :", tinggi_badan_mahasiswa1, tinggi_badan_mahasiswa2, tinggi_badan_mahasiswa3,
      tinggi_badan_mahasiswa4, tinggi_badan_mahasiswa5)
 
#Lebih ringkas pakai list
data_tinggi_badan_mahasiswa = [165, 163, 170, 180, 185]
print("data tinggi badan mahasiswa :", data_tinggi_badan_mahasiswa)

data tinggi badan mahasiswa : 165 163 170 180 185
data tinggi badan mahasiswa : [165, 163, 170, 180, 185]


In [7]:
#Akan sangat lama jika menulis kumpulan data seperti ini
nama_mahasiswa_1 = "Matthew Alfredo"
nama_mahasiswa_2 = "Ricky Sitorus"
nama_mahasiswa_3 = "Joshua Silitonga"
nama_mahasiswa_4 = "Risky Siahan"
nama_mahasiswa_5 = "Pakhomis Havel"
print("data nama mahasiswa :", nama_mahasiswa_1, nama_mahasiswa_2, nama_mahasiswa_3, nama_mahasiswa_4, nama_mahasiswa_5)
 
#Lebih ringkas pakai list
data_nama_mahasiswa = ["Matthew Alfredo", "Ricky Sitorus", "Joshua Silitonga", "Risky Siahan", "Pakhomis Havel"]
print("data nama mahasiswa :", data_nama_mahasiswa, type(data_nama_mahasiswa))

data nama mahasiswa : Matthew Alfredo Ricky Sitorus Joshua Silitonga Risky Siahan Pakhomis Havel
data nama mahasiswa : ['Matthew Alfredo', 'Ricky Sitorus', 'Joshua Silitonga', 'Risky Siahan', 'Pakhomis Havel'] <class 'list'>


In [8]:
#Akan sangat lama jika menulis kumpulan data seperti ini
data_bool1 = True
data_bool2 = True
data_bool3 = False
print("data boolean yang terekap :", data_bool1, data_bool2, data_bool3)
 
#Lebih ringkas pakai list
data_boolean_yang_terekap = [True, True, False]
print("data boolean yang terekap :", data_boolean_yang_terekap)

data boolean yang terekap : True True False
data boolean yang terekap : [True, True, False]


In [1]:
#tipe list juga mendukung tipe data campuran di dalamnya
tipe_data_campuran = [1, "Matthew Alfredo -> Korea Selatan", True, 2, "Joshua Silitonga -> Malaysia", True,
                      "Risky Siahan -> Germany", True, "Son Goku -> Indonesia", False]
print(tipe_data_campuran)

[1, 'Matthew Alfredo -> Korea Selatan', True, 2, 'Joshua Silitonga -> Malaysia', True, 'Risky Siahan -> Germany', True, 'Son Goku -> Indonesia', False]


In [2]:
#cara alternatif membuat list
#range(awal, akhir-1, increment (harus integer))
data_range = range(0,50,2)
data_list = list(data_range)
print(data_list)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]


In [3]:
#membuat list dengan for
list = [i for i in range(0,20, 2)]
print(list)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [4]:
#membuat list dengan for dan if
list1 = [i for i in range(0,20,2) if i != 2]
print("list 1:", list1)
 
list2 = [i for i in range(0,20) if i%2 == 0]
print("list 2:", list2)
 
list3 = [i for i in range(0,20) if i%2 != 0]
print("list 3:", list3)

list 1: [0, 4, 6, 8, 10, 12, 14, 16, 18]
list 2: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
list 3: [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [5]:
mahasiswa_D3TI2020 = ("Joshua", "Matthew", "Ricky", "Risky", "Pakhomis", "Kevin", "Feronika")

In [6]:
# pip install --upgrade pip

In [7]:
# pip install numpy

In [8]:
#Perbedaan array dan list
import numpy as np
a = np.array([1, 2, 3, 4])
b = [1, 2, 3, 4]
print(a, b)

[1 2 3 4] [1, 2, 3, 4]


In [9]:
#Perbedaan array dan list
a = np.array([1, 2, 3, 4])
a = a+1
b = [1, 2, 3, 4]
b = b + [1]
print(a)
print(b)

[2 3 4 5]
[1, 2, 3, 4, 1]


In [11]:
#cara advance membuat array
a = np.array( ([1,2,3],[4,5,6]), dtype = float )
print(a)
 
#membuat array dengan iterable
iterable = (x*2 for x in range(5))
a = np.fromiter(iterable, dtype = float)
print(a)
 
#multitype array
dtipe = [('nama','S255'), ('tinggi', int)]
data = [('Ricky Sitorus', 170),
        ('Risky Siahan', 172),
        ('Joshua Silitonga', 180)]
a = np.array(data, dtype = dtipe)
print(a)

[[1. 2. 3.]
 [4. 5. 6.]]
[0. 2. 4. 6. 8.]
[(b'Ricky Sitorus', 170) (b'Risky Siahan', 172) (b'Joshua Silitonga', 180)]


In [12]:
#membuat vector
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2.5, 3, 4, 5])
print(a,b)

[1 2 3 4 5] [1.  2.5 3.  4.  5. ]


In [13]:
#membuat vector dengan arange
a = np.arange(1, 10, 2)
print(a)

[1 3 5 7 9]


In [14]:
#membuat vector dengan linspace
a = np.linspace(1, 10, 4)
print(a)

[ 1.  4.  7. 10.]


In [15]:
#membuat matriks atau array multidimensi
a = np.array ( [(1, 2, 3), (4, 5, 6), (7, 8, 9)] )
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
#membuat matriks nol
a = np.zeros([5,5]) # ukuran 5x5
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
#membuat matriks identitas
a = np.identity(3) # ukuran 3x3
print(a)
 
b = np.eye(3) # ukuran 3x3
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
#membuat matriks dengan elemen 1
a = np.ones([5,5]) #ukuran 5x5
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
#operasi elementwise (mengoperasikan setiap elemen yang berkorespondensi dengan elemen yang sama)
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
hasil1 = a+b
hasil2 = a-b
hasil3 = a*b
hasil4 = a/b
hasil5 = a**2
print("hasil 1 =", hasil1)
print("hasil 2 =", hasil2)
print("hasil 3 =", hasil3)
print("hasil 4 =", hasil4)
print("hasil 5 =", hasil5)

hasil 1 = [ 7  9 11 13 15]
hasil 2 = [-5 -5 -5 -5 -5]
hasil 3 = [ 6 14 24 36 50]
hasil 4 = [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
hasil 5 = [ 1  4  9 16 25]


In [20]:
#operator Elementwise ada masalah di perkalian matriks karena mengalikan per elemen
a = np.array( [(1,2,3), (4,5,6)] )
b = np.array( [(3,4,5), (3,4,5)] )
hasil = a*b
print("hasil =", hasil)

hasil = [[ 3  8 15]
 [12 20 30]]


In [21]:
#perkalian matriks
a = np.array( [(1,2,3),(4,5,6)] )
b = np.array( [(1,2,3),(1,2,3),(1,2,3)] )
hasil_perkalian_matriks = np.dot(a,b)
print(hasil_perkalian_matriks)

[[ 6 12 18]
 [15 30 45]]
